誕生日のライブラリを使用するプログラムに変更
ryo-yoshikawa/processing-csv_text pull request #2
Opened 2021-04-06 07:47 UTC by ryo-yoshikawa

issue: #1
* happybirthday.gem(https://takanamito.hateblo.jp/entry/2018/05/15/091820)を使用して、プログラムを作成しました。
* requireは一番上とご指摘もいただいたので、移動しました。

2021-04-06 08:52 UTC, kazuhisa commented
ライブラリを利用することで、問題が簡単に解決できることが分かりましたね！
今のままだと、
```shell
$ gem install happybirthday
```
を実行して、ライブラリをインストールしないと実行することができません。
ライブラリのインストールをユーザーに意識させるようにしてみましょう。

```shell
$ bundle init
```
でGemfileを作成します。必要なライブラリはこのファイルで管理できます。
Gemfileをエディタで開き
`# gem "rails"`と書かれている箇所を`gem "happybirthday"` に書き換えましょう。
```shell
$ bundle install
```
で、ライブラリをインストールすることができます。利用者もGemfileが存在することで「ライブラリのインストールが必要なんだな」ということを認識できます。

Gemfileでライブラリを管理する場合、プログラムを実行するときに頭に`bundle exec`をつけましょう。
```shell
$  bundle exec ruby prosessing-csv_text.rb
```
ですね。

作成された、GemfileとGemfile.lockをcommitしてもう一度pushしてみてください。

2021-04-08 07:51 UTC, ryo-yoshikawa commented
@kazuhisa 
追加してみました

2021-04-08 07:57 UTC, kazuhisa requested changes

2021-04-08 07:57 UTC, kazuhisa commented on Gemfile
> +# gem "happybirthday"
いやいや、先頭の#を外してください。今のままだとコメントになっていますよ。

2021-04-12 06:11 UTC, ryo-yoshikawa commented
@kazuhisa 
修正したしました。
`$  bundle exec ruby prosessing-csv_text.rb`
で動くことも確認してます。

2021-04-12 06:34 UTC, kazuhisa commented
@ryo-yoshikawa 
私がマージできるように権限調整してもらえますか？

2021-04-14 00:49 UTC, merged